config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :products_orders
  resources :deliveries, only: [:edit, :update]
  post 'store/cart/update_quantity' => 'products_orders#update_quantity', 
        as: 'cart_update_quantity'
  get 'store/cart/:id' => 'store#cart', as: 'store_cart'
  get 'privacy_policy' => 'store#privacy_policy', as: 'store_privacy_policy'
  get 'terms_of_use' => 'store#terms_of_use', as: 'store_terms_of_use'
  get 'contact' => 'store#contact_us', as: 'store_contact_us'
  match 'search' => 'store#search', as: 'store_search', via: [:get, :post]
  get 'search/:id' => 'store#search_products', as: 'store_search_products'
  get 'product/:id' => 'store#product', as: 'store_product'
  root 'store#index'
end

app/views/shared/_carousel_slider.html.erb
<div class="content_top">
  <div class="wrap">
    <h3>Latest Products</h3>
  </div>
  <div class="line"></div>
  <div class="wrap">
    <div class="ocarousel_slider">  
      <div class="ocarousel example_photos" data-ocarousel-perscroll="3">
        <div class="ocarousel_window">
          <% @carousel_products.each do |carousel_product| %>
            <%= link_to store_product_path(carousel_product.product_id) do %>
              <%= image_tag carousel_product.photo %>
              <p><%= carousel_product.description %></p>
            <% end %>
          <% end %>
        </div>
        <span>
          <a href="#" data-ocarousel-link="left" style="float: left;" class="prev"> </a>
          <a href="#" data-ocarousel-link="right" style="float: right;" class="next"> </a>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_categories.html.erb
<% categories.each do |c| %>
  <li>

    <% if c.categories.present? %>
      <%= link_to c.title, '#' %>
      <ul>
        <%= render partial: 'shared/categories', locals: { categories: c.categories } %>
      </ul>
    <% else %>
      <%= link_to c.title, store_search_products_path(c.id) %>
    <% end %>
  </li>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>The form contains <%= pluralize(object.errors.count, "error") %>.</h2>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
  <div class="wrap">  
    <div class="copy_right">
      <p>Copy rights 2016&copy;. All rights Reseverd. Developed by <a href="https://github.com/geovo851">Georgy</a> &nbsp;| Template by  <a href="http://w3layouts.com" target="_blank">W3Layouts</a> </p>
    </div> 
    <div class="footer-nav">
      <ul>
        <li><%= link_to 'Terms of Use', store_terms_of_use_path %> : </li>
        <li><%= link_to 'Privacy Policy', store_privacy_policy_path %> : </li>
        <li><%= link_to 'Contact Us', store_contact_us_path %></li>
      </ul>
     </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="wrap">
    <div class="header_top">
      <div class="logo">
        <%= link_to(image_tag('logo.png'), root_path) %>
      </div>
      <div class="header_top_right">
        <div class="search_box">
          <span>Search</span>
          <%= form_tag store_search_path do %>
            <%= text_field_tag :search_text, params[:search_text] %>
            <%= submit_tag '' %>
          <% end %>
          <div class="clear"></div>
        </div>
      </div>
      <div class="clear"></div>
    </div>

    <div class="navigation">
      <a class="toggleMenu" href="#">Menu</a>

      <ul class="nav">
        <li>
          <%= link_to 'Home', root_path %>
        </li>
        <%= render partial: 'shared/categories', locals: { categories: @categories } %>
        <li>
          <%= link_to 'Contact Us', store_contact_us_path %>
        </li>
        <li>
          <%= link_to 'Cart', store_cart_path(@cart) %>
        </li>
      </ul>
      <span class="left-ribbon"> </span>
      <span class="right-ribbon"> </span>
    </div>

    <% if yield(:slider) == 'slider' %> 
      <div class="header_bottom">
        <div class="slider-text">
          <h2>Electronics store <br/> sit amet, consectetur adipisicing eli</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit<br/> sed do eiusmod tempor incididunt</p>
          <a href="https://github.com/geovo851">Ruby on Rails Developer</a>
        </div>
        <div class="slider-img">
          <%= image_tag 'slider-img.png' %>
        </div>
       <div class="clear"></div>
      </div>
    <% end %>
  </div>
</div>