config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :products_orders
  resources :deliveries, only: [:edit, :update]
  post 'store/cart/update_quantity' => 'products_orders#update_quantity', 
        as: 'cart_update_quantity'
  get 'store/cart/:id' => 'store#cart', as: 'store_cart'
  get 'privacy_policy' => 'store#privacy_policy', as: 'store_privacy_policy'
  get 'terms_of_use' => 'store#terms_of_use', as: 'store_terms_of_use'
  get 'contact' => 'store#contact_us', as: 'store_contact_us'
  match 'search' => 'store#search', as: 'store_search', via: [:get, :post]
  get 'search/:id' => 'store#search_products', as: 'store_search_products'
  get 'product/:id' => 'store#product', as: 'store_product'
  root 'store#index'
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def edit
    @payments = Payment.all
    @categories = Category.where(category_id: nil)
  end

  def update
    @cart.order = true
    @cart.status = 'expect'
    if @cart.update(orders_params)
      message = "Your order is accepted. The manager will call you. Your order №#{@cart.id}"
      flash[:success] = message
      set_cart

      redirect_to root_path
    else
      flash[:error] = "The order is not accepted."
      @payments = Payment.all
      @categories = Category.where(category_id: nil)

      render 'edit'
    end
  end

  private
    def orders_params
      params.require(:order).permit(:payment_id, :delivary_adress, :phone_number)
    end
end

app/views/deliveries/edit.html.erb
<% provide(:title, "Order") %>

<div class="main">
  <div class="content">

    <div class="content_bottom">
      <div class="wrap">
        <div class="content-bottom-left">
          <%= render partial: 'store/all_categories',
                     locals: { root_categoreis: @categories } %>

          <div class="buters-guide">
            <h3>Buyers Guide</h3>
            <p><span>We want you to be happy with your purchase.</span></p> 
            <p>So we're committed to giving you all the tools to make the right decision with minimum fuss. </p>
          </div>
          <%= render 'store/banners' %>
        </div>
        <div class="content-bottom-right">
          <h3>Order</h3>
          <%= form_for @cart, url: delivery_path(@cart) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <div>
              <%= f.label :delivary_adress %>
              <div>
                <%= f.text_area :delivary_adress, cols: 45, rows: 5 %>
              </div>
            </div>

            <div>
              <%= f.label :phone_number %>
              <div>
                <%= f.text_field :phone_number, size: 15 %>
              </div>
            </div>

            <div>
              <%= f.label :payment %>
              <div>
                <%= f.collection_select(:payment_id, @payments, 
                            :id, :type_of_payment, {:prompt => 'Please select payment'}) %>
              </div>
            </div>

            <div>
                <%= f.submit 'Buy', class: "btn_delivery"%>
                <%= link_to 'Сancel', root_path, class: "btn_cancel" %>
            </div>
          <% end %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>