config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :products_orders
  resources :deliveries, only: [:edit, :update]
  post 'store/cart/update_quantity' => 'products_orders#update_quantity', 
        as: 'cart_update_quantity'
  get 'store/cart/:id' => 'store#cart', as: 'store_cart'
  get 'privacy_policy' => 'store#privacy_policy', as: 'store_privacy_policy'
  get 'terms_of_use' => 'store#terms_of_use', as: 'store_terms_of_use'
  get 'contact' => 'store#contact_us', as: 'store_contact_us'
  match 'search' => 'store#search', as: 'store_search', via: [:get, :post]
  get 'search/:id' => 'store#search_products', as: 'store_search_products'
  get 'product/:id' => 'store#product', as: 'store_product'
  root 'store#index'
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  before_action :set_categories

  def index
    @products = Product.first(12)
    @carousel_products = CarouselProduct.first(12)
    @title_products = 'Popular Products'
  end

  def search_products
    if params[:root_category]
      @products = Product.where(category_id: all_category(params[:id])).page(params[:page]).per(12)
    else
      @products = Product.where(category_id: params[:id]).page(params[:page]).per(12)
    end
    @category = Category.find(params[:id])
    @title_products = @category.title
  end

  def product
    @product = Product.includes(:product_specifications, :properties).find(params[:id])
    @products_order = ProductsOrder.new
    @popular_products = PopularProduct.includes(:product).first(3)
    @carousel_products = CarouselProduct.first(12)
  end

  def contact_us
    @message = Message.new
  end

  def search
    @products = Product.search(params[:search_text], params[:page])
    @title_products = 'Results found:'
  end

  def terms_of_use
  end

  def privacy_policy
  end

  def cart
  end

  private
    def set_categories
      @categories = Category.where(category_id: nil)
    end

    def all_category root_category_id
      find_category Category.where(id: root_category_id)
    end

    def find_category categories, categories_id = []
      categories.each do |c|
        if c.categories.present?
          find_category c.categories, categories_id
        else
          categories_id << c.id
        end
      end
      categories_id
    end
end

app/views/store/_all_categories.html.erb
<div class="categories">
  <ul>
    <h3>Browse All Categories</h3>

    <% root_categoreis.each do |c| %>
      <li><%= link_to c.title, store_search_products_path(c.id, root_category: true) %></li>
    <% end %>
  </ul>
</div>

app/views/store/_banners.html.erb
<div class="add-banner">
  <%= image_tag 'camera.png' %>
  <div class="banner-desc">
    <h4>Electronics</h4>
    <a href="#">More Info</a>
  </div>
  <div class="clear"></div>
</div>

<div class="add-banner add-banner2">
  <%= image_tag 'computer.png' %>
  <div class="banner-desc">
    <h4>Computers</h4>
    <a href="#">More Info</a>
  </div>
  <div class="clear"></div>
</div>

app/views/store/_popular_products.html.erb
<h3>Popular Products</h3>
<ul class="popular-products">
  <% @popular_products.each do |popular_product| %>
    <li>
      <h4><%= link_to popular_product.product.name,
                      store_product_path(popular_product.product_id) %></h4>
      <%= link_to(image_tag(popular_product.photo),
                  store_product_path(popular_product.product_id)) %>
      <div class="price-details">
        <div class="price-number">
          <p><span class="rupees line-through">$<%= popular_product.product.price %> </span> &nbsp; <span class="rupees">$<%= popular_product.promotional_price %> </span></p>
        </div>
        <div class="add-cart">
          <h4><%= link_to 'More Info', store_product_path(popular_product.product_id) %></h4>
        </div>
        <div class="clear"></div>
      </div>
    </li>
  <% end %>
</ul>

app/views/store/_product_tab.html.erb
<div class="product_desc">
  <div id="horizontalTab">
    <ul class="resp-tabs-list">
      <li>Specifications</li>
      <li>Description</li>
      <li>Buying Options</li>
      <div class="clear"></div>
    </ul>
    <div class="resp-tabs-container">
      <div class="product-specifications">
        <ul>
          <% @product.product_specifications.each do |specification| %>
            <li>
              <span class="specification-heading"><%= specification.property.title %></span>
              <span><%= specification.value %></span>
              <div class="clear"></div>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="product-tags">
        <p><%= @product.description %></p>
      </div>

      <div class="review">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
  </div>
</div>

app/views/store/_products.html.erb
<h3><%= @title_products %></h3>

<% i = 0 %>
<% products.each do |product| %>
  <% i < 4 ? i += 1 : i = 1 %>

  <% if i == 1 %>
    <div class="section group">
  <% end %>

      <div class="grid_1_of_4 images_1_of_4">
        <h4><%= link_to truncate(product.name, length: 60), store_product_path(product) %></h4>

        <%= link_to store_product_path(product) do %>
          <%= image_tag(product.photo) %>
        <% end %>

        <div class="price-details">
          <div class="price-number">
            <p><span class="rupees">$<%= product.price %> </span></p>
          </div>
          <div class="add-cart">
            <h4><%= link_to 'More Info', store_product_path(product) %></h4>
          </div>
          <div class="clear"></div>
        </div>
      </div>

  <% if i == 4 %>
    </div>
  <% end %>

<% end %>

app/views/store/cart.html.erb
<% provide(:title, 'Cart') %>

<div class="main">
  <div class="content">

    <div class="content_bottom">
      <div class="wrap">
        <div class="content-bottom-left">
          <%= render partial: 'all_categories',
                     locals: { root_categoreis: @categories } %>

          <div class="buters-guide">
            <h3>Buyers Guide</h3>
            <p><span>We want you to be happy with your purchase.</span></p> 
            <p>So we're committed to giving you all the tools to make the right decision with minimum fuss. </p>
          </div>
          <%= render 'banners' %>
        </div>
        <div class="content-bottom-right">
          <h3>Cart</h3>
          <% if @cart.products_orders.empty? %>
            <b>Cart empty.</b>
          <% else%>

            <div class="header-cart">
              <table>
                <thead>
                 <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Sum</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @cart.products_orders.each do |p| %>
                    <tr>
                      <td><%= p.product.name if p.product %></td>
                      <td>
                        <%= text_field_tag :quantity, p.quantity, size: 1,
                            class: 'quantity', id: p.id %>
                      </td>
                      <td><%= p.price %></td>
                      <td><%= p.quantity * p.price %></td>
                      <td>
                        <%= button_to 'x', products_order_path(p),
                              method: :delete,
                              data: { confirm: 'Are you sure?' },
                              class: "btn btn-primary btn-xs" %>
                      </td>
                    </tr>

                  <% end %>
                </tbody>
              </table>

              <p>Total sum: <span id="cart-totalsum"><%= @cart.total_sum %></span></p>
              <%= button_to 'Buy', edit_delivery_path(@cart), method: :get, 
                          class: "btn_buy_cart" %>
            </div>
            
          <% end %>

        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>

app/views/store/contact_us.html.erb
<% provide(:title, "Contact Us") %>

<div class="main">
  <div class="wrap">
    <div class="preview-page">
      <div class="contact_info">
        <div class="map">
          <iframe width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265&amp;output=embed"></iframe><br><small><a href="https://maps.google.co.in/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265" style="color:#888;text-align:left;font-size:0.85em">View Larger Map</a></small>
        </div>
      </div>
      <div class="contact-form">
        <h3>Contact Us</h3>
        <%= render partial: 'messages/form', locals: { message: @message } %>
      </div>
    </div>
  </div>
</div>

app/views/store/index.html.erb
<% provide(:title, 'Home') %>
<% provide(:slider, 'slider') %>

<div class="main">
  <div class="content">

    <%= render 'shared/carousel_slider' %>

    <div class="content_bottom">
      <div class="wrap">
        <div class="content-bottom-left">
          <%= render partial: 'all_categories',
                     locals: { root_categoreis: @categories } %>

          <div class="buters-guide">
            <h3>Buyers Guide</h3>
            <p><span>We want you to be happy with your purchase.</span></p> 
            <p>So we're committed to giving you all the tools to make the right decision with minimum fuss. </p>
          </div>
          <%= render 'banners' %>
        </div>
        <div class="content-bottom-right">
          <%= render partial: 'products', locals: { products: @products } %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>

app/views/store/product.html.erb
<% provide(:title, @product.name) %>

<div class="main">
  <div class="wrap">
    <div class="preview-page">

      <div class="section group">
        <div class="cont-desc span_1_of_2">
          <ul class="back-links">
            <li><%= link_to 'Home', root_path %> ::</li>
            <li><%= link_to 'Product Page', store_product_path(@product) %> ::</li>
            <li><%= @product.name %></li>
            <div class="clear"> </div>
          </ul>

          <div class="product-details"> 
            <div class="grid images_3_of_2">
              <ul id="etalage">
                <% @product.photos.each do |photo| %>
                  <li>
                    <%= image_tag photo.small, class: 'etalage_thumb_image' %>
                    <%= image_tag photo.large, class: 'etalage_source_image' %>
                  </li>
                <% end %>
              </ul>
            </div>

            <div class="desc span_3_of_2">
              <h2><%= @product.name %></h2>
              <p><%= @product.description %></p>
              <div class="price">
                <p>Price: <span>$<%= @product.price %></span></p>
              </div>
              <div class="available">
                <ul>
                  <li><span>Model:</span> &nbsp; Model <%= @product.model %></li>
                  <li><span>Shipping Weight:</span>&nbsp; <%= @product.weight %> kg</li>
                  <li><span>Units in Stock:</span>&nbsp; <%= @product.units_in_stock %></li>
                  </ul>
              </div>
              <div class="share-desc">
                <div id="add_to_cart">
                  <%= form_for @products_order do |f| %>
                    <%= hidden_field_tag(:product_id, @product.id) %>
                    <%= hidden_field_tag(:price, @product.price) %>
                    <%= f.submit 'Add to Cart' %>
                  <% end %>
                  </div>

                <div class="clear"></div>
              </div>

              <div class="colors-share">
                <div class="social-share">
                  <h4>Share Product</h4>
                  <ul>
                    <li><a class="share-face" href="#"> </a></li>
                    <li><a class="share-twitter" href="#"> </a></li>
                    <li><a class="share-google" href="#"> </a></li>
                    <li><a class="share-rss" href="#"> </a></li>
                    <div class="clear"> </div>
                  </ul>
                </div>
                <div class="clear"></div>
              </div>
            </div>
            <div class="clear"></div>
          </div>
          <%= render 'product_tab' %>
        </div>
        <div class="rightsidebar span_3_of_1 sidebar">
          <%= render 'popular_products' %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/carousel_slider' %>
</div>

app/views/store/search.html.erb
<% provide(:title, 'Search') %>

<div class="main">
  <div class="content">
    <div class="content_bottom">
      <div class="wrap">
        <div class="content-bottom-left">
          <%= render partial: 'all_categories',
                     locals: { root_categoreis: @categories } %>
          <div class="buters-guide">
            <h3>Buyers Guide</h3>
            <p><span>We want you to be happy with your purchase.</span></p> 
            <p>So we're committed to giving you all the tools to make the right decision with minimum fuss. </p>
          </div>
          <%= render 'banners' %>
        </div>
        <div class="content-bottom-right">
          <% if @products.empty? %>
            <div class="not-found">Products not found</div>
          <% else %>
            <div id="products">
              <%= render partial: 'products', locals: { products: @products } %>
            </div>
            <div id="paginator", class="paginate-centre">
              <%= paginate @products, :remote => true %>
            </div>
          <% end %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>

app/views/store/search_products.html.erb
<% provide(:title, @category.title) %>

<div class="main">
  <div class="content">
    <div class="content_bottom">
      <div class="wrap">
        <div class="content-bottom-left">
          <%= render partial: 'all_categories',
                     locals: { root_categoreis: @categories } %>
          <div class="buters-guide">
            <h3>Buyers Guide</h3>
            <p><span>We want you to be happy with your purchase.</span></p> 
            <p>So we're committed to giving you all the tools to make the right decision with minimum fuss. </p>
          </div>
          <%= render 'banners' %>
        </div>
        <div class="content-bottom-right">
          <div id="products">
            <%= render partial: 'products', locals: { products: @products } %>
          </div>
          <div id="paginator", class="paginate-centre">
            <%= paginate @products, :remote => true %>
          </div>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>

app/views/store/search_products.js.erb
$('#products').html('<%= escape_javascript render(partial: "products", locals: { products: @products }) %>');

$('#paginator').html('<%= escape_javascript(paginate(@products, :remote => true).to_s) %>');

app/views/store/terms_of_use.html.erb
<% provide(:title, 'Terms of Use') %>

<div class="main">
  <div class="content">

    <div class="content_bottom">
      <div class="wrap">
        <div class="content-bottom-left">
          <%= render partial: 'all_categories',
                     locals: { root_categoreis: @categories } %>

          <div class="buters-guide">
            <h3>Buyers Guide</h3>
            <p><span>We want you to be happy with your purchase.</span></p> 
            <p>So we're committed to giving you all the tools to make the right decision with minimum fuss. </p>
          </div>
          <%= render 'banners' %>
        </div>
        <div class="content-bottom-right">
          <h3>Terms of Use</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>